<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PharmaPOS.Application\PharmaPOS.Application.csproj" />
    <ProjectReference Include="..\PharmaPOS.Infrastructure\PharmaPOS.Infrastructure.csproj" />
    <ProjectReference Include="..\PharmaPOS.Persistence\PharmaPOS.Persistence.csproj" />
    <ProjectReference Include="..\PharmaPOS.Domain\PharmaPOS.Domain.csproj" />
    <ProjectReference Include="..\PharmaPOS.Shared\PharmaPOS.Shared.csproj" />
    <ProjectReference Include="..\..\tools\PharmaPOS.MedWinImport\PharmaPOS.MedWinImport.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.69.0" />
    <PackageReference Include="Google.Apis.Drive.v3" Version="1.69.0.3769" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.9" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
    <PackageReference Include="OpenCvSharp4" Version="4.10.0.20240616" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.10.0.20240616" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.10.0.20240616" />
    <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.10.0.20240616" />
    <PackageReference Include="PDFsharp" Version="6.2.1" />
    <PackageReference Include="SSH.NET" Version="2024.2.0" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.10" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
    <PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.14" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <AssemblyName>PharmaPOS</AssemblyName>
    <RootNamespace>PharmaPOS.WPF</RootNamespace>
    <Version>1.3.1</Version>
    <FileVersion>1.3.1.0</FileVersion>
    <InformationalVersion>1.3.1</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico" />
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.Production.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
